# Generated by Django 3.1.7 on 2024-02-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roundNumber', models.PositiveSmallIntegerField()),
                ('eventId', models.CharField(max_length=8)),
                ('division', models.CharField(choices=[('MPO', 'MPO'), ('FPO', 'FPO'), ('MP40', 'MP40'), ('MA1', 'MA1')], default='MPO', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roundScores', models.JSONField()),
            ],
        ),
    ]
